# Generated by Django 5.1.4 on 2025-05-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_squashed_0011_populate_initial_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_banned",
            field=models.BooleanField(default=False),
        ),
    ]
